<script>
    /*
    function stopDialog(){
        $("#StopDialog").dialog({
            width: 450,
            modal: true,
            buttons: {
                "Cancel": function() {$(this).dialog("destroy");},
                "Stop": function (){startStopServer("Stop")}
            }
        });   
    }
    */
    //$("#servers_stop").on('click', function (event){
    function deleteDialog(serverIds) {
        $("#DeleteDialog").dialog({
            width: 450,
            modal: true,
            buttons: {
                "Cancel": function() {$(this).dialog("destroy");},
                "OK": function () {
                    $(this).dialog("destroy");
                    console.log("OK: serverIds="+serverIds);
                    deleteServers(serverIds, true)
                }
            }
        });
    }

    function deleteServers(serverIds, verified) {
        if (typeof(verified)==='undefined') verified = false;
        console.log("deleteServers: serverIds="+serverIds);
        
        if (!verified) {
            deleteDialog(serverIds);
            return;
        }
        jWaiting(		
            'Deleting servers...',
            {
                autoHide : false, // added in v2.0
                clickOverlay : false, // added in v2.0
                HorizontalPosition : 'center',
                VerticalPosition : 'center',
                ShowOverlay : true
            }
        );

        $.ajax({
            type: "post",
            url: "<?=$app_path?>/ajax/delete-servers",
            data: {
                //id: "<$viewData->serverRec->id?>",
                //id: getSessionItem("serverId"),
                serverIds: serverIds
            },
            dataType: "json",
            success: function(data) {
                if (data.success != true)
                    alert("deleteServers: stop: PHP failure")
                location.assign('<?=$app_path?>/servers');
            },
            failure: function(data) {
                alert("deleteServer: stop: Ajax failure");
                location.reload(true);
            }
        });                    
    }

</script>
