    <div class="toolbar">
        <div class="left">
            <a id="servers_new" class="servers_toolbar" 
               href="<?=$app_path?>/servers/create">New</a>
            <a id="servers_manage" class="servers_toolbar default_off single_on" 
               href="#">Manage</a>
            <a id="servers_start" class="servers_toolbar default_off stopped_on" href="#">Start</a>
            <a id="servers_stop" class="servers_toolbar default_off running_on" href="#">Stop</a>
            <a id="servers_restart" class="servers_toolbar default_off running_on" href="#">Restart</a>
            <a id="servers_delete" class="servers_toolbar default_off single_on" 
               href="#">Delete</a>
            <a id="servers_clone" class="servers_toolbar default_off single_on" 
               href="#">Clone</a>
        </div>
        <div class="right">
            <a id="servers_filter" class="servers_toolbar default_off" href="#">Filter</a>
            <a id="servers_refresh" class="servers_toolbar" href="#">Refresh</a>
            <a id="servers_help" class="servers_toolbar" href="#">Help</a>
        </div>
        <div class="clear"></div>
    </div>

<?php include('start-stop-server.phtml'); ?>
<?php include('delete-servers.phtml'); ?>

<!--?php include('CloneDialog.html.php'); ?-->
<div id="loadCloneDialog"></div>

<?php include('servers-toolbar-js.phtml'); ?>
