    <script>
        $("#servers_new").on('click', function() {location.assign('<?=$app_path?>/servers/create')});
        $("#servers_refresh").on('click', function() {window.location.reload(true);} );

        $("#servers_help").on('click', function() {myLayout.toggle('east');});
        $("#servers_stop").on('click', function() {startStopServer(selServerId, "Stop")} );
        $("#servers_start").on('click', function() {startStopServer(selServerId, "Start")} );
        $("#servers_restart").on('click', function() {startStopServer(selServerId, "Restart")} );
        
        $("#servers_clone").on('click', loadCloneDialog);
        $("#servers_delete").on('click', function () {deleteServers(selServerIds);});

        //$("#servers_new").button({ icons: {primary: "ui-icon-document"} });
        //$("#servers_manage").button({ icons: {primary: "ui-icon-gear"} });
        //$("#servers_start").button({ icons: {primary: "ui-icon-play"} });
        //$("#servers_stop").button({ icons: {primary: "ui-icon-stop"} });
        //$("#servers_restart").button({ icons: {primary: "ui-icon-refresh"} });
        //$("#servers_delete").button({ icons: {primary: "ui-icon-trash"} });
        //$("#servers_clone").button({ icons: {primary: "ui-icon-copy"} });
        //$("#servers_filter").button({ icons: {primary: "ui-icon-search"} });
        //$("#servers_refresh").button({ icons: {primary: "ui-icon-refresh"} });
        //$("#servers_help").button({ icons: {primary: "ui-icon-help"} });

        //$(".default_off").button("disable");
        
        function loadCloneDialog() {
            console.log("loadCloneDialog: entry");
            $("#loadCloneDialog").load(
                "<?=$app_path?>/servers/load-clone-dialog",
                {serverId: selServerId},
                function() {cloneDialog();} // cloneDialog is not known when script runs
            );
        }
        
        //jqGrid selServerIdsChanged listener
        $(document).on("selServerIdsChange", function(e) {
            // get running status of 1st row
            if (selServerIds.length > 0) {
                var selRow = myGrid.jqGrid('getRowData', selServerIds[0]);
                console.log("search = " + selRow['status'].search('Running') );
                // text search the cell
                if (selRow['status'].search('Running') >= 0) {
                    status = 'Running';
                }
                else {
                    status = 'Stopped';
                }
            }
            console.log("status = " + status );
            
            //set uri of refresh button
            var uri = '<?=$app_path?>/servers';
            $.each(selServerIds, function(index, serverId) {
                if (index == 0)
                    uri += '?';
                else 
                    uri += '&';
                uri += "items[]=" + serverId;
            });
            uri = encodeURI(uri);
            console.log("uri="+uri);
            $("#servers_refresh").attr("href", uri);

            //disable buttons that default to off
            $(".default_off").button("disable");
            //$("#servers_filter").button("enable");
            
            //enable buttons that should be on
            if (selServerIds.length == 0)
                return;
            
            if (selServerIds.length > 0)
                $("#servers_delete").button("enable");
            
            if (selServerIds.length == 1) {
                $("#servers_manage").attr("href", "<?=$app_path?>/servers/manage/"+selServerIds[0]);
                $(".single_on").button("enable");
                //set start, stop, restart depending on status
                if (status == 'Running')
                    $(".running_on").button("enable");
                else
                    $(".stopped_on").button("enable");
            }
            
            return;
        });
        
    </script>
