    <div class="toolbar">
        <div class="left">
            <a id="servers_new" class="servers_toolbar" 
               href="<?=$app_path?>/servers/create">New</a>
            <a id="servers_manage" class="servers_toolbar default_off single_on" 
               href="#">Manage</a>
            <a id="servers_start" class="servers_toolbar default_off stopped_on" href="#">Start</a>
            <a id="servers_stop" class="servers_toolbar default_off running_on" href="#">Stop</a>
            <a id="servers_restart" class="servers_toolbar default_off running_on" href="#">Restart</a>
            <a id="servers_delete" class="servers_toolbar default_off single_on" 
               href="#">Delete</a>
            <a id="servers_clone" class="servers_toolbar default_off single_on" 
               href="#">Clone</a>
        </div>
        <div class="right">
            <a id="servers_filter" class="servers_toolbar default_off" href="#">Filter</a>
            <a id="servers_refresh" class="servers_toolbar" href="#">Refresh</a>
            <a id="servers_help" class="servers_toolbar" href="#">Help</a>
        </div>
        <div class="clear"></div>
    </div>

<?php include('start-stop-server.phtml'); ?>
<?php include('delete-servers.phtml'); ?>

<!--?php include('CloneDialog.html.php'); ?-->
<div id="loadCloneDialog"></div>

    <script>
        $("#servers_refresh").on('click', function() {window.location.reload(true);} );

        $("#servers_help").on('click', function() {myLayout.toggle('east');});
        $("#servers_stop").on('click', function() {startStopServer(selServerId, "Stop")} );
        $("#servers_start").on('click', function() {startStopServer(selServerId, "Start")} );
        $("#servers_restart").on('click', function() {startStopServer(selServerId, "Restart")} );
        
        $("#servers_clone").on('click', loadCloneDialog);
        $("#servers_delete").on('click', function () {deleteServers(selServerIds);});

        $("#servers_new").button({ icons: {primary: "ui-icon-document"} });
        $("#servers_manage").button({ icons: {primary: "ui-icon-gear"} });
        $("#servers_start").button({ icons: {primary: "ui-icon-play"} });
        $("#servers_stop").button({ icons: {primary: "ui-icon-stop"} });
        $("#servers_restart").button({ icons: {primary: "ui-icon-refresh"} });
        $("#servers_delete").button({ icons: {primary: "ui-icon-trash"} });
        $("#servers_clone").button({ icons: {primary: "ui-icon-copy"} });
        $("#servers_filter").button({ icons: {primary: "ui-icon-search"} });
        $("#servers_refresh").button({ icons: {primary: "ui-icon-refresh"} });
        $("#servers_help").button({ icons: {primary: "ui-icon-help"} });

        $(".default_off").button("disable");
        
        function loadCloneDialog() {
            console.log("loadCloneDialog: entry");
            jqLoadClone = $("#loadCloneDialog");
            $("#loadCloneDialog").load(
                "<?=$app_path?>/servers/load-clone-dialog",
                {serverId: selServerId},
                function() {cloneDialog()} // cloneDialog is not known when script runs
            );
        }
        
        function setServerToolbarState(selServerIds, status) {
            var uri = '<?=$app_path?>/servers';
            $.each(selServerIds, function(index, serverId) {
                if (index == 0)
                    uri += '?';
                else 
                    uri += '&';
                uri += "items[]=" + serverId;
            });
            uri = encodeURI(uri);
            console.log("uri="+uri);
            $("#servers_refresh").attr("href", uri);

            $(".default_off").button("disable");
            //$("#servers_filter").button("enable");
            
            if (selServerIds.length == 0)
                return;
            
            if (selServerIds.length > 0)
                $("#servers_delete").button("enable");
            
            if (selServerIds.length == 1) {
                $("#servers_manage").attr("href", "<?=$app_path?>/servers/manage/"+selServerIds[0]);
                $(".single_on").button("enable");
                //set start, stop, restart depending on status
                if (status == 'Running')
                    $(".running_on").button("enable");
                else
                    $(".stopped_on").button("enable");
            }
            
            return;
        }

    </script>
