    <div class="toolbar">
        <div class="left">
            <a id="servers_close" class="servers_toolbar" 
               href="<?=$app_path?>/servers?items[]=<?=$viewData->serverRec->id?>">
                Close</a>
            <a id="servers_start" class="servers_toolbar default_off stopped_on" href="#">Start</a>
            <a id="servers_stop" class="servers_toolbar default_off running_on" href="#">Stop</a>
            <a id="servers_restart" class="servers_toolbar default_off running_on" href="#">Restart</a>
            <a id="servers_delete" class="servers_toolbar default_off single_on" href="#">Delete</a>
            <a id="servers_clone" class="servers_toolbar default_off single_on" href="#">Clone</a>
        </div>
        <div class="right">
            <a id="servers_refresh" class="servers_toolbar" href="#">Refresh</a>
            <a id="servers_help" class="servers_toolbar" href="#">Help</a>
        </div>
        <div class="clear"></div>
    </div>

    <?php $logger->info('include_path='.print_r(get_include_path(), true) ); ?>
    <?php include(__DIR__.'/../servers/start-stop-server.phtml'); ?>
    <?php include(__DIR__.'/../servers/delete-servers.phtml'); ?>

    <div id="loadCloneDialog"></div>

<?php include('manage-toolbar-js.phtml'); ?>
    