<form title="Rename Server" width="600" method="post" 
    id="rename_server_form" style="display: none" class="edit_server" 
    action="/servers/14965" accept-charset="UTF-8">
    <div class="error" style="display:none"><span></span></div>
    <div style="margin:0;padding:0;display:inline">
        <p>Please modify the server name below</p>
        <input type="hidden" value="14965" name="server[id]" id="server_id" />
        <table style="width: 100%" class="properties">
            <tbody><tr style="vertical-align: top;">
                    <th style="width: 120px;">
                        <label for="serverName">Name</label></th>
                    <td>
                        <input type="text" value="<?=$viewData->serverRec->serverName?>" 
                            name="serverName" id="serverName" size="40"
                            title=""
                            class="ui-widget-content ui-corner-all"
                            type="text" required="" />
                        <img title="One line description of the server, it must be unique." 
                            src="<?=$app_images->helpIcon?>" /></td>
                </tr>
                <tr style="vertical-align: top;">
                    <th>
                        <label for="publicDNS">Domain Name</label></th>
                    <td>
                        <input type="text" value="<?=$viewData->serverRec->publicDNS?>" 
                            id="publicDNS" size="40" name="publicDNS" 
                            title=""
                            class="ui-widget-content ui-corner-all"
                            type="text" required="" />
                        <?=DNS_ZONE?>
                        <img title="Please choose your Domain Name." 
                            src="<?=$app_images->helpIcon?>" /></td>
                </tr>
            </tbody>
        </table>
    </div>
</form>

<?php include('rename-dialog-js.phtml'); ?>
