    <center class="tiny">
        © 2012-2013, <a href="<?=SERVICE_URL?>"><?=SERVICE_NAME?></a>. All rights reserved.
        <img alt="|" class="footer_bar" src="<?=$app_images->imagePath?>/footer_bar.png" align="absmiddle">
        <a href="<?=SERVICE_URL?>" class="helpdesk_link" target="_blank">Support</a>
        <img alt="|" class="footer_bar" src="<?=$app_images->imagePath?>/footer_bar.png" align="absmiddle">
        <a href="<?=SERVICE_URL?>" target="_blank">
            Privacy Policy
        </a>
        <img alt="|" class="footer_bar" src="<?=$app_images->imagePath?>/footer_bar.png" align="absmiddle">
        <a href="<?=SERVICE_URL?>" target="_blank">
            Terms of Use
        </a>
    </center>
