    <script src="<?=$app_path?>/js/jquery-layout/1.3.0rc30.74/jquery.layout-latest.js"></script>
    <script src="<?=$app_path?>/js/jquery-validation/1.10.0/jquery.validate.js"></script>

    <link rel="stylesheet" type="text/css" href="<?=$app_path?>/js/jquery-jnotify/2.1/jquery/jNotify.jquery.css" />
    <script src="<?=$app_path?>/js/jquery-jnotify/2.1/jquery/jNotify.jquery.js"></script>
    
    <script src="<?=$app_path?>/assets/console.js"></script>

    <?=isset($viewData->head)? $viewData->head : ''?>
