    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?=SERVICE_NAME?> Cloud Hosting</title>

    <!--link rel="stylesheet" type="text/css" 
          href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/themes/redmond/jquery-ui.css" /-->
    <link rel="stylesheet" type="text/css" 
          href="<?=$app_path?>/js/jquery-ui/1.9.2/css/redmond/jquery-ui-1.9.2.custom.css" />
    
    <link rel="stylesheet" type="text/css" href="<?=$app_path?>/js/jquery-layout/1.3.0rc30.74/layout-default.css" />
    <link rel="stylesheet" type="text/css" href="<?=$app_path?>/assets/console.css" />

    <!--script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.js"></script-->
    <script src="<?=$app_path?>/js/jquery/1.8.3/jquery-1.8.3.js"></script>
    
    <!-- TOOLTIPS DOES NOT WORK WITH 1.8.24! script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.js"></script-->
    <script src="<?=$app_path?>/js/jquery-ui/1.9.2/js/jquery-ui-1.9.2.custom.js"></script>
    
    <script src="<?=$app_path?>/js/jquery-ui-markup/jquery.ui.markup.js"></script>
