    <link rel="stylesheet" type="text/css" href="<?=$app_path?>/js/jquery-dcmegamenu/1.3.3/css/dcmegamenu.css" />
    <link rel="stylesheet" type="text/css" href="<?=$app_path?>/js/jquery-dcmegamenu/1.3.3/css/skins/blue.css" />
    <script type='text/javascript' src='<?=$app_path?>/js/jquery-hoverIntent/r6/jquery.hoverIntent.minified.js'></script>
    <script type='text/javascript' src='<?=$app_path?>/js/jquery-dcmegamenu/1.3.3/jquery.dcmegamenu.1.3.3.js'></script>    

<script type="text/javascript">
$(document).ready(function($){
	$('#mega-menu-4').dcMegaMenu({
		rowItems: '1',
		speed: 'fast',
		effect: 'fade'
	});
});
</script>

<div class="demo-container"><!--style="max-height:60px!important"-->
<div class="blue"> <!--style="max-height:60px!important"-->  
<ul id="mega-menu-4" class="mega-menu">
	<li><a <?=$this->hrefAndSelected('')?> >
            <img valign="middle" src="<?=$app_path?>/images/fff-icons/application_view_tile.png" alt="Application_view_tile">
            Dashboard</a></li>
        <li><a <?=$this->hrefAndSelected('news')?> >
            <img valign="middle" src="<?=$app_path?>/images/fff-icons/newspaper.png" alt="Newspaper">
            News</a></li>
        <li>
            <a href="#">
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/server.png" alt="Server">
                SERVERS</a>
        <ul type="none" class="nav_links">
            <li>
                <a <?=$this->hrefAndSelected('servers')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/server.png" alt="Server">
                Servers</a>
            </li>
            <li>
                <a <?=$this->hrefAndSelected('backups')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/drive_key.png" alt="Drive_key">
                Backups</a>
            </li>
            <li>
                <a <?=$this->hrefAndSelected('monitoring')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/chart_bar.png" alt="Chart_bar">
                Monitoring</a>
            </li>
            <li>
                <a <?=$this->hrefAndSelected('scheduling')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/calendar.png" alt="Calendar">
                Scheduling</a>
            </li>
        </ul>
        </li>
        <li>
            <a href="#">
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/weather_clouds.png" alt="Weather_clouds">
                CLOUDS</a>
        <ul type="none" class="nav_links">
            <li>
                <a <?=$this->hrefAndSelected('clouds')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/weather_clouds.png" alt="Weather_clouds">
                Manage</a>
            </li>
            <li>
                <a <?=$this->hrefAndSelected('servers/import')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/server_add.png" alt="Server_add">
                Import Servers</a>
            </li>
        </ul>
        <li>
            <a href="#">                
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/user.png" alt="User">
                SETTINGS</a>
        <ul type="none" class="nav_links">
            <li>
                <a <?=$this->hrefAndSelected('account/user')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/user.png" alt="User">
                User</a>
            </li>
            <li>
                <a <?=$this->hrefAndSelected('account/billing')?> >
                <img valign="middle" src="<?=$app_path?>/images/fff-icons/creditcards.png" alt="Creditcards">
                Billing</a>
            </li>
        </ul>
        </li>

</ul>
</div>
</div>
