<h3>Manage Server</h3>
<h4>Create Backup</h4>
A backup is a snapshot of the state of the server at a given time. You can restore a backup into a running server at any given time in the Backups section.
<h4>Assign IP</h4>
Each machine has a single IP address associated with it. The IP address can either be static or dynamic. Dynamic addresses will change between reboots.
<h4>Connect</h4>
Provides information on how to connect via ssh to your server and allows you to download your private SSH key in PEM and PPK formats.
<h4>System Log</h4>
Provides the output log of the server boot process. Useful for debugging purposes.
<h4>Resize Machine</h4>
You can resize your server at any time. As part of the process the server will automatically stopped and restarted if it is currently running. It is possible to downgrade or upgrade the server type and increase the size of the disk. It is not possible to change the operating system architecture between 32bit and 64bit machines or decrease the size of the disk.
<h4>More info</h4>
<p>
    For additional information, please visit the
    <a target="_blank" href="http://www.infusionappdev.com">inFusion Wiki</a>
    and our
    <a target="_blank" class="helpdesk_link" href="http://www.infusionappdev.com">Support Portal</a>
</p>
