<!-- add {action_name}-help.phtml and HelpPlugin will find it -->
<h3>Server Management</h3>
    <ul>
        <li>
            <b>New</b>
            Allows you to create and configure new servers. The servers will automatically be launched
        </li>
        <li>
            <b>Stop</b>
            Stop the selected servers. The data will persist and you can start the server again at any time.
        </li>
        <li>
            <b>Start</b>
            Start the selected servers that were previously stopped.
        </li>
        <li>
            <b>Restart</b>
            Restart the selected servers.
        </li>
        <li>
            <b>Delete</b>
            Stop the machine and remove the persistent storage. Once you do this, the data will be lost forever. It will still be possible to restore previous backups.
        </li>
        <li>
            <b>Manage</b>
            Manage an existing server, including creating backups, changing the IP address and resizing.
        </li>
        <li>
            <b>Go to Application</b>
            Visit the URL for your application.
        </li>
    </ul>


    <h4>More info</h4>
    <p>
        For additional information, please visit the
        <a target="_blank" href="http://www.infusionappdev.com">inFusion Wiki</a>
        and our
        <a target="_blank" class="helpdesk_link" href="http://www.infusionappdev.com">Support Portal</a>
    </p>

