<?php include PORTABLE_PHTML; ?>

<div id="content-main" class="ui-layout-center">
    <h2 class="header">Server Management</h2>
    <?php include('servers/servers-toolbar.phtml'); ?>
    <div id="grid_container" class="ui-layout-content">
        <table id="server_grid"></table> 
        <div id="server_pager"></div> 
    </div>
</div>
<div id="content-details" class="ui-layout-south">
    <h2 class="header">Details</h2>
    <div id="details_container" class="ui-layout-content">
        <div id="details-empty">
            <p>Select a single server to show its details.</p>
        </div>
        <div id="details-loading" class="filtered">
            <p><img align="absmiddle" src="<?=$app_path?>/images/preloader-icon.gif"> Loading...</p></div>
        <div id="details-contents" class="filtered"></div>
    </div
</div>

<link rel="stylesheet" type="text/css" href="<?=$app_path?>/js/jqgrid/4.4.1/css/ui.jqgrid.css" />
<style>
    /*.ui-jqgrid tr.jqgrow td {font-size:12px} */
    .ui-jqgrid th {font-size:12px!important; padding: 2px; font-weight: bold!important; }
    .ui-jqgrid td {font-size:12px!important; padding: 2px; font-weight: normal!important; }
</style>
<script src="<?=$app_path?>/js/jqgrid/4.4.1/i18n/grid.locale-en.js" type="text/javascript"></script>
<script src="<?=$app_path?>/js/jqgrid/4.4.1/jquery.jqGrid.min.js" type="text/javascript"></script>

<?php include 'servers-js.phtml'; ?>
