<script type="text/javascript">
var myGrid = $("#server_grid");

var selServerId = null,
    selServerIds = [];
    //selServerName = null,   //set in serverDetails
    //selPublicDNS = null,    //ditto
    //selCloudAccountId = null;   //ditto

$(document).ready(function(){ 
    var jqLoading = $("#details-loading"),
        jqContents = $("#details-contents"),        
        jqEmpty = $("#details-empty");

  myGrid.jqGrid({
    url:'<?=$app_path?>/ajax/get-servers-grid',
    //url:'http://localhost/console/ajax/getServersGrid',     //CORS: server: header('Access-Control-Allow-Origin: *');
    datatype: 'xml',
    mtype: 'GET',
    autowidth: true,
    height: "100%",
    loadonce: true,
    rowNum: null,
    //pager: '#server_pager',
    //rowNum:10,
    //rowList:[10,20,30],
    //viewrecords: true,
    sortname: 'serverName',
    sortorder: 'asc',
    gridview: true,
    multiselect: true,
    multiboxonly: true,
    deselectAfterSort: false,
    //caption: 'My first grid'
    colNames:['Name','Status', 'Operating System','Server Type','Server Location','Cloud Account'],
    colModel :[ 
      {name:'name', index: 'serverName'}, //width:55}, 
      {name:'status', index: 'status'}, //width:90}, 
      {name:'os', index: 'osTypeId'}, //width:80}, 
      {name:'type', index: 'serverTypeId'}, // width:80}, 
      {name:'location', index: 'locationTypeId'}, // width:80}, 
      {name:'cloud', index: 'cloudAccountId'} // width:150} 
    ],
    loadComplete: function() {
        console.log("datatype = " + myGrid.jqGrid('getGridParam', 'datatype') );
        
        //now local sorting
        myGrid.jqGrid('setGridParam', {datatype: 'local'});
        
        console.log("datatype = " + myGrid.jqGrid('getGridParam', 'datatype') );
        
        $.each(<?=$viewData->selRowsJS?>, function(index, rowId) {
            console.log('setting row='+rowId);
            myGrid.jqGrid('setSelection', rowId, true);
        });
    },
    //onSelectRow: doSelectRow,
    onSelectRow: function(id, isSelected) {
        console.log("Row selected: " + id + " " + isSelected);
        
        //selServerId = null;
        //selServerName = null;   //set in serverDetails
        //selPublicDNS = null;    //ditto
        //selCloudAccountId = null;   //ditto

        selServerIds = $(this).jqGrid('getGridParam', 'selarrrow');
        selServerId = selServerIds.length == 1 ? selServerIds[0] : null;
        
        $(document).trigger("selServerIdsChange");
        return;
    }
  }); 
  
  //load server details selServerIdsChanged listener
  $(document).on("selServerIdsChange", function(e) {
        console.log("selServerIds.length="+selServerIds.length);
        if (selServerIds.length != 1) {
            cancelLoad = true;
            jqLoading.addClass("filtered");
            jqContents.addClass("filtered");        
            jqEmpty.removeClass("filtered");
            return;
        }

        // only one selected -- update details
        console.log("Only one row selected");
        //Lib::setSessionItem("serverId", selServerIds[0]);
        selServerId = selServerIds[0];
        jqEmpty.addClass("filtered");        
        jqLoading.removeClass("filtered");
        jqContents.addClass("filtered");
        cancelLoad = false;
        jqContents.load(
            "<?=$app_path?>/servers/load-server-details",
            {serverId: selServerId},
            function() {
                if (cancelLoad)
                    return;
                jqEmpty.addClass("filtered");        
                jqLoading.addClass("filtered");
                jqContents.removeClass("filtered");
            }
        );
        return;
  });
  
}); 
</script>
